"""Protocol definitions for hardware backends."""

from __future__ import annotations

from typing import Protocol


class PCA9685Backend(Protocol):
    def set_pwm_freq(self, freq: float) -> None: ...
    def set_motor_pwm(self, channel: int, duty: int) -> None: ...
    def set_servo_pulse(self, channel: int, pulse_us: float) -> None: ...
    def close(self) -> None: ...


class ADCBackend(Protocol):
    pcb_version: int

    def read_voltage(self, channel: int) -> float: ...
    def close(self) -> None: ...


class GPIOBackend(Protocol):
    def read_line_sensor(self, pin: int) -> bool: ...
    def set_output(self, pin: int, state: bool) -> None: ...
    def read_distance_cm(self, trigger: int, echo: int, max_m: float) -> float: ...
    def close(self) -> None: ...
